
# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard 'shell' do
  watch(/(.*).txt/) {|m| `tail #{m[0]}` }
end
guard 'shell' do
  watch(/index.md/) {|m|
    `slideshow build #{m[0]} -t shower ` }
end
